routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');


Route::resource('provider', 'ProveedorController');

app/Models/Proveedor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Proveedor extends Model
{
    protected $table = 'provider';


    protected $primaryKey = 'id_provider';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['nit', 'nombre', 'direccion', 'telefono'];

    public static function providers()
    {
        $query = self::query();
        return $query->get();
    }
}

app/Models/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
       //
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.dashboard.index');
    }
}

app/Http/Controllers/ProveedorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Proveedor;

class ProveedorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $providers = Proveedor::providers();
        return view('provider.index', compact('providers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('provider.create-edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    { 
        try {
            $data = $request->all();
            $provider = new Proveedor;
            $provider->fill($data);
            $provider->estado = 'Activo';
            $provider->save();
    
            return view('provider.create-edit');
        
        } catch (\Exception $e) {
            \Log::error(sprintf('%s:%s', 'ProveedorController:store', $e->getMessage()));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Proveedor  $Proveedor
     * @return \Illuminate\Http\Response
     */
    public function show()
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Proveedor  $Proveedor
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!is_numeric($id)){
            throw new \Exception("Este valor no es numérico", $id);            
        }

        $provider = Proveedor::find($id);
        if(!$provider instanceof Proveedor){
            throw new \Exception("Este proveedor no exite en la base de datos", $id);            
        }

        return view('provider.create-edit', compact('provider'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Proveedor  $Proveedor
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $data = $request->all();
            $provider = Proveedor::find($id);
            $provider->fill($data);
            $provider->save();
    
            return view('provider.create-edit', compact('provider'));
            
        } catch (\Exception $e) {
            \Log::error(sprintf('%s:%s', 'ProveedorController:update', $e->getMessage()));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Proveedor  $Proveedor
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(!is_numeric($id)){
            throw new \Exception("Este valor no es numérico", $id);            
        }

        $provider = Proveedor::find($id);
        if(!$provider instanceof Proveedor){
            throw new \Exception("Este proveedor no exite en la base de datos", $id);            
        }

        $provider->delete();

        return redirect('/provider');
    }
}

resources/views/admin/dashboard/index.blade.php
@section('title', 'Home')
@extends('admin.layouts.app')
@section('dashboard')
<div class="background-dashboard">
</div>
@endsection

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <title>CRUD</title>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="Gradient Able Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs." />
    <meta name="keywords" content="bootstrap, bootstrap admin template, admin theme, admin dashboard, dashboard template, admin template, responsive" />
    <meta name="author" content="codedthemes" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @include('admin.shared.head')
    <style>
        .mCSB_container {
            width: 100% !important;
        }
    </style>
</head>
<!-- Menu-compact layout -->

<body class="skin-blue">
    <div class="wrapper">

        <!-- Header -->
        @include('admin.shared.header')

        <!-- Sidebar -->
        @include('admin.shared.sidebar')

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">

            <!-- Main content -->
            <section class="content">
                <!-- Your Page Content Here -->
                @yield('content')
            </section><!-- /.content -->
        </div><!-- /.content-wrapper -->

    </div><!-- ./wrapper -->
    @include('admin.shared.scripts')
    @stack('functions')
</body>

</html>

resources/views/admin/shared/head.blade.php
<!-- Bootstrap 3.3.2 -->
<link href="{{ asset('adminlte/bower_components/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" />
<!-- Font Awesome Icons -->
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<!-- Ionicons -->
<link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
<!-- Theme style -->
<link href="{{ asset('adminlte/dist/css/AdminLTE.min.css')}}" rel="stylesheet" type="text/css" />
<!-- AdminLTE Skins. We have chosen the skin-blue for this starter
              page. However, you can choose any other skin. Make sure you
              apply the skin class to the body tag so the changes take effect.
        -->
<link href="{{ asset('adminlte/dist/css/skins/skin-blue.min.css')}}" rel="stylesheet" type="text/css" />
@stack('styles')

resources/views/admin/shared/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo"><b>Admin</b>LTE</a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <!-- inner menu: contains the messages -->
                            <ul class="menu">
                                <li>
                                    <!-- start message -->
                                    <a href="#">
                                        <div class="pull-left">
                                            <!-- User Image -->
                                            <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image" />
                                        </div>
                                        <!-- Message title and timestamp -->
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <!-- The message -->
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li><!-- end message -->
                            </ul><!-- /.menu -->
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li><!-- /.messages-menu -->

                <!-- Notifications Menu -->
                <li class="dropdown notifications-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <li>
                                    <!-- start notification -->
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li><!-- end notification -->
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                <!-- Tasks Menu -->
                <li class="dropdown tasks-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <!-- Inner menu: contains the tasks -->
                            <ul class="menu">
                                <li>
                                    <!-- Task item -->
                                    <a href="#">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <!-- The progress bar -->
                                        <div class="progress xs">
                                            <!-- Change the css width attribute to simulate progress -->
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li><!-- end task item -->
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ asset('adminlte//dist/img/user2-160x160.jpg') }}" class="user-image" alt="User Image" />
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">Alexander Pierce</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image" />
                            <p>
                                Alexander Pierce - Web Developer
                                <small>Member since Nov. 2012</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/shared/scripts.blade.php
<!-- jQuery 2.1.3 -->
<script src="{{ asset('adminlte/bower_components/jquery/dist/jquery.min.js') }}"></script>
<!-- Bootstrap 3.3.2 JS -->
<script src="{{ asset('adminlte/bower_components/bootstrap/dist/js/bootstrap.min.js') }}" type="text/javascript"></script>
<!-- AdminLTE App -->
<script src="{{ asset('adminlte/dist/js/adminlte.min.js') }}" type="text/javascript"></script>

@stack('scripts')

resources/views/admin/shared/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('adminlte/dist/img/user2-160x160.jpg') }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>Alexander Pierce</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            <li class="header">HEADER</li>
            <!-- Optionally, you can add icons to the links -->
            <li class="active"><a href="{{ route('provider.index') }}"><span>Proveedor</span></a></li>
        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/home.blade.php
@extends('plantilla')

@section('seccion')
<h1>Proveedores</h1>

<div <div class="container">
  <a href="{{ route('c_proveedor')}}" class="btn btn-primary"> Crear Proveedor</a>
</div>
<div <div class="container">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nit</th>
        <th scope="col">Nombre</th>
        <th scope="col">Direccion</th>
        <th scope="col">Telefono</th>
        <th scope="col">Id Producto</th>
        <th scope="col">Estado</th>
      </tr>
    </thead>
    <tbody>
      @foreach($proveedores as $proveedor)

      <tr>
        <th scope="row">{{$proveedor->Nit}}</th>
        <td>{{$proveedor->Nombre}}</td>
        <td>{{$proveedor->Direccion}}</td>
        <td>{{$proveedor->Telefono}}</td>
        <td>{{$proveedor->Id_producto}}</td>
        <td>{{$proveedor->Estado}}</td>
      </tr>

      @endforeach()

    </tbody>
  </table>
</div>


@endsection

resources/views/provider/create-edit.blade.php
@extends('admin.layouts.app')
@section('content')
<div class="row">
  <!-- left column -->
  <div class="col-md-12">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Crear proveedor</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <form role="form" action="{{ isset($provider) ? route('provider.update', $provider->id_provider) : route('provider.store') }}" method="POST">
        @if(isset($provider))
          @method('PUT')
        @endif
        <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
        <div class="box-body">
          <div class="row">
            <!-- left column -->
            <div class="col-md-6">
              <div class="form-group">
                <label for="provider_name">Nombre</label>
                <input type="text" name="nombre" class="form-control" value="{{ isset($provider) ? $provider->nombre : '' }}" id="provider_name" placeholder="Nombre">
              </div>
            </div>
            <!-- left column -->
            <div class="col-md-6">
              <div class="form-group">
                <label for="provider_phone">Teléfono</label>
                <input type="text" name="telefono" class="form-control" value="{{ isset($provider) ? $provider->telefono : '' }}" id="provider_phone" placeholder="Teléfono">
              </div>
            </div>
          </div>
          <div class="row">
             <!-- left column -->
            <div class="col-md-6">
              <div class="form-group">
                <label for="provider_direction">Dirección</label>
                <input type="text" name="direccion" class="form-control" value="{{ isset($provider) ? $provider->direccion : '' }}" id="provider_direction" placeholder="Nombre">
              </div>
            </div>
            <!-- left column -->
            <div class="col-md-6">
              <div class="form-group">
                <label for="provider_nit">NIT</label>
                <input type="text" name="nit" class="form-control" value="{{ isset($provider) ? $provider->nit : '' }}" id="provider_nit" placeholder="Teléfono">
              </div>
            </div>
          </div>
        </div>
        <!-- /.box-body -->
        <div class="box-footer">
          <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
      </form>
    </div>
    <!-- /.box -->
  </div>
</div>
@endsection

resources/views/provider/index.blade.php
@extends('admin.layouts.app')
@section('content')
<section class="content">
  <div class="row">
    <div class="col-md-12">
      <div class="box">
        <div class="box-header with-border">
          <h3 class="box-title">Proveedores</h3>
        </div>
        <div>
          <a href="{{ route('provider.create') }}" class="btn btn-primary btn-flat">
            Crear proveedor
          </a>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table class="table table-bordered">
            <tbody>
              <tr>
                <th style="width: 10px">#</th>
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Nit</th>
                <th>Acción</th>
              </tr>
              <tr>
                @foreach($providers as $provider)
                <td>{{ $provider->id_provider }}</td>
                <td>{{ $provider->nombre }}</td>
                <td>{{ $provider->direccion }}</td>
                <td>{{ $provider->telefono }}</td>
                <td>{{ $provider->nit }}</td>
                <td>
                  <a class="btn btn-primary btn-flat" href="{{ route('provider.edit', $provider->id_provider) }}"><i class="fa fa-pencil"></i></a>
                  <form action="{{ route('provider.destroy', $provider->id_provider) }}" method="post">
                      {{ method_field('delete') }}
                      <input type="hidden" name="_token" id="csrf-token" value="{{ Session::token() }}" />
                      <button class="btn btn-danger btn-flat" type="submit"><i class="fa fa-trash"></i></button>
                  </form>
                </td>
                @endforeach
              </tr>
            </tbody>
          </table>
        </div>
        <!-- /.box-body -->
        <div class="box-footer clearfix">
          <ul class="pagination pagination-sm no-margin pull-right">
            <li><a href="#">«</a></li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">»</a></li>
          </ul>
        </div>
      </div>
      <!-- /.box -->
    </div>
  </div>
  </div>
  @endsection